__init__.py
from app import *

app.py
#!/usr/bin/env python
# -*- coding: UTF-8 -*-

import sys, os

import config
import controllers

from flask import Flask, render_template


# Initialize Flask app with the template folder address
app = Flask(__name__,template_folder='templates')

# Register the controllers
app.register_blueprint(controllers.main)
app.register_blueprint(controllers.resume)
app.register_blueprint(controllers.project)

@app.errorhandler(404)
def page_not_found(error):
    return render_template('error404.html'), 404

controllers/__init__.py
from main import *
from resume import *
from project import *
from blog import *

controllers/main.py
from flask import *
import config

main = Blueprint('main', __name__, template_folder='templates')

@main.route('/')
def main_route():
    return render_template("index.html")

controllers/project.py
from flask import *
import config

project = Blueprint('project', __name__, template_folder='templates')

@project.route('/project')
def project_route():
    return render_template("project.html")

controllers/resume.py
from flask import *
import config

resume = Blueprint('resume', __name__, template_folder='templates')

@resume.route('/resume')
def resume_route():
    return render_template("resume.html")

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<link rel="stylesheet" type="text/css" href="static/css/main-style.css">
	<link href="https://fonts.googleapis.com/css?family=Quicksand" rel="stylesheet">
	<title>Xiang Liu</title>
</head>
<body>
	<div class="home-page">
		<a href="http://xiangliux.com"><h1>Xiang Liu</h1></a>
		<div id="blue-stripe"></div>
		<div id="red-stripe"></div>

		<ul class="menu">
			<li><a href="static/resume.pdf">Resumé</a></li>
			<li><a href="projects.html">Projects</a></li>
			<li><a href="http://github.com/BruceLiux">GitHub</a></li>
			<li><a href="contact.html">Contact</a></li>
		</ul>
		{% block content %}{% endblock %}
	</div>


</body>
</html>

templates/error404.html
{% extends "jumbo.html" %}
{% block content %}   
	<p>Ooops, still working on it. Coming soon!</p>
		
{% endblock %}

templates/index.html
{% extends "jumbo.html" %}
{% block content %}   
  <div class="row">
        <div class="col-md-4">
          <h2>Resume</h2>
          <p>My official resume written in LaTex. Including education experience, work and project experience. PDF version is provided. </p>
          <!-- <p><a class="btn btn-default" href="{{url_for('resume.resume_route')}}" role="button">View details &raquo;</a></p> -->
          <p><a class="btn btn-default" href="static/resume.pdf" role="button">View details &raquo;</a></p>


        </div>
        <div class="col-md-4">
          <h2>Project</h2>
          <p>Here lists my selected project with brief introduction. Including a search engine based on PageRank, an Android App for DJI drone and a 3D visualization implementation. </p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
       	</div>
        <div class="col-md-4">
          <h2>Blog</h2>
          <p>This serves as my personal technical blog. The main purpose is to share my ideas and insights for a digital life. Still working on it</p>
          <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
        </div>
  </div>

      
  <div class="row">
        <div class="col-md-12">
        <!-- <script type="text/javascript">window.onload=loadimg();</script> -->
        
        <img id="photo"  style="width: 100%"/>
        <script type="text/javascript" src="static/js/loadimg.js"></script>
        </div>
        
  </div><!-- /home-page -->	

{% endblock %}

templates/jumbo.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="My Portfolio">
    <meta name="author" content="Xiang Liu">
    <!-- <link rel="icon" href="../../favicon.ico"> -->

    <title>Xiang Liu's portfolio</title>

    <!-- Bootstrap core CSS -->
    <link href="static/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="static/css/carousel.css" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="http://portfolio.xiangliux.com">Xiang Liu's Portfolio</a>
        </div>
<!--         <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div> -->
      </div>
    </nav>

    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>Hello, world!</h1>
        <p>Welcome to my Website! My name is Xiang Liu and I am a first Master year student at University of Michigan.<i>"It always seems impossible until it's done."</i></p>
        <!-- <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p> -->
      </div>
    </div>

    <div class="container">

      {% block content %}{% endblock %}
    
      <hr>
      <footer>
        <p>&copy; Xiang Liu's Portfolio. 2017</p>
      </footer>

    </div> <!-- /container -->



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="static/bootstrap/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="static/bootstrap/js/bootstrap.min.js"></script>
    <script type="static/js/loadimg.js"></script>
    <script type="text/javascript" async
    src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML">
    </script>
  </body>
</html>

templates/project.html
{% extends "jumbo.html" %}
	{% block content %}   
	<!-- START THE FEATURETTES -->
	<div class="row featurette">
	<div class="col-md-7">
	  <h2 class="featurette-heading">First featurette heading. <span class="text-muted">It'll blow your mind.</span></h2>
	  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
	</div>
	<div class="col-md-5">
	  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
	</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette">
	<div class="col-md-7 col-md-push-5">
	  <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
	  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
	</div>
	<div class="col-md-5 col-md-pull-7">
	  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
	</div>
	</div>

	<hr class="featurette-divider">

	<div class="row featurette">
	<div class="col-md-7">
	  <h2 class="featurette-heading">And lastly, this one. <span class="text-muted">Checkmate.</span></h2>
	  <p class="lead">Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Praesent commodo cursus magna, vel scelerisque nisl consectetur. Fusce dapibus, tellus ac cursus commodo.</p>
	</div>
	<div class="col-md-5">
	  <img class="featurette-image img-responsive center-block" data-src="holder.js/500x500/auto" alt="Generic placeholder image">
	</div>
	</div>

	<hr class="featurette-divider">

	<!-- /END THE FEATURETTES -->
		
{% endblock %}

templates/resume.html
{% extends "jumbo.html" %}
{% block content %}   
<p lang="latex">
\documentclass{resume} % Use the custom resume.cls style
\linespread{0.85}
\usepackage[left=0.7in,top=0.45in,right=0.7in,bottom=0.45in]{geometry} % Document margins
\newcommand{\tab}[1]{\hspace{.2667\textwidth}\rlap{#1}}
\newcommand{\itab}[1]{\hspace{0em}\rlap{#1}}
\name{Xiang Liu} % Your name
\address{2156 Stone Road, Ann Arbor, MI 48105} % Your address
\address{(734)-358-9809 $\mid$ portfolio.xiangliux.com $\mid$ xliux@umich.edu} % Your phone number and email

\begin{document}
%----------------------------------------------------------------------------------------
%	OBJECTIVE SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Objective}

{\small Seeking a Software Development Engineering Intern position utilizing professional skills in web development.}

\end{rSection}
%----------------------------------------------------------------------------------------
%	EDUCATION SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Education}
{\small 
{\bf University of Michigan, Ann Arbor, MI} \hfill {\em May 2018} 
\\ Master of Electrical and Computer Engineering \hfill { GPA: 3.3/4}
\\ Coursework: Web Database $\&$ Information Systems; Introduction to Algorithm \\
\\
{\bf Zhejiang University, Hangzhou, China} \hfill {\em July 2016} 
\\ Bachelor of Science in Information and Communication Engineering \hfill { GPA: 3.77/4}
\\ Coursework: Coursework: Data structure $\&$ Algorithm; Intro to Computer Organization

}
\end{rSection}


%----------------------------------------------------------------------------------------
%	WORK EXPERIENCE SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Work Experience}
{\small 
\begin{rSubsection}{SecNeo Security Service Co.}{Hangzhou, China}{Web Engineering Intern}{September 2015-November 2015}
\item Designed a web crawler in Python to monitor Android app status information
\item Monitored illegal download and track download URLs
\end{rSubsection}
}

\end{rSection}

%----------------------------------------------------------------------------------------
%	PROJECT EXPERIENCE SECTION
%----------------------------------------------------------------------------------------
\begin{rSection}{Project Experience}
{\small
\begin{rSubsection}{University of Michigan}{Ann Arbor, MI}{Web development projects for EECS 485}{September 2016-December 2016}
\item Developed a photo album website with python in the server side and HTML/JavaScript on client side. Build a database for the album website with MySQL. Implemented user authentication and used sessions.
\item Created a common interface (the API). Client-side will fetch data using AJAX and insert data dynamically.
\item Implemented a single machine, multi-process, multi-threaded MapReduce server in python.
\item Built an integrated search engine with information retrieval based on tf-idf and PageRank scores. Used Hadoop library to implement large file indexing with MapReduce.
\end{rSubsection}

\begin{rSubsection}{Zhejiang University}{Hangzhou, China}{Android App Developer}{March 2015-July 2015}
\item Developed an Android DJI drone app as a ground station control system
\item Implemented drone real-time user self-tracking system. Drone would follow user’s move with the speed and location information provided by user and return the video in real-time. These features went beyond the official ground station in mobile platform at that time and helped DJI to optimize their ground station application
\item Won Second Prize in DJI App developer competition
\end{rSubsection}

\begin{rSubsection}{University of Michigan}{Ann Arbor, MI}{Undergraduate Research Assistant}{July 2015-September 2015}
\item Designed a software-based radio system by using GNU Radio and Python. Developed a high level flow graph so that transmitter and receiver could work in duplex mode/
\item Custom designed blocks to implement parameterized pulse-position modulation that reduced system power requirement. Implemented a predefined header which could evoke the receiver when needed.
\item Customized USRP FPGA RX signal path and implemented real time packet detection. User could use this system to test their chips with customized signal.
\end{rSubsection}

\begin{rSubsection}{Zhejiang University}{Hangzhou, China}{Undergraduate Research Assistant}{Jan 2015-March 2015}
\item Implemented a webcam-based real-time human gaze tracking. Use gradient-based Hough transform to pupil localization and modified the key parameters in Gaussian filter; Optimized the threshold value to accurate result.
\item Applied orthogonal face detectors to preclude noise region. Improve minimal tracking recognition range to 15 $cm^2$.
\end{rSubsection}
}

\end{rSection}

%----------------------------------------------------------------------------------------
%	TECHNICAL STRENGTHS SECTION
%----------------------------------------------------------------------------------------

\begin{rSection}{Technical Strengths}

{\small
Languages: C++, Java, Python, MySQL, JavaScript, HTML, MATLAB, Verilog, LaTex 
}
\end{rSection}
\end{document}
</p>	
{% endblock %}